### PR TITLE
Testing To Do list: part 1

### PR DESCRIPTION
**Pull request by shyusu4**
## PR Description

- Created a test file `(crud.test.js)` for a file containing the add item and delete item functions.
- Used `describe()` method
- Mocked HTML to test if add/delete functions add or remove exactly one element.

### CODE REVIEW

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a contribution from your partner yet its a group project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by degisew** [comment]
Hello @danmainah, we all are here and both of us contributed. would you mind to check it
 again?

**Comment by danmainah** [comment]
> Hello @danmainah, we all are here and both of us contributed. would you mind to check it again?

I have checked it kindly ask for a review.

**Review by codecaiine — APPROVED** [review]
Hi @shyusu4 @degisew , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good project implementation :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- All tests passed :heavy_check_mark: 

Screenshot from 2022-08-25 13-53-33

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
